metting_manager/config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :groups
  get 'groups/index'
  get 'users/search'
  post 'users/search'
  get 'users/index'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: 'users/registrations',
                                }
  root 'welcome#index'
  resources :users do            #tao moi quan he trong chung
    resources :profiles do
    end
    resources :groups do  
      get 'memberlists/add'
      post 'memberlists/add'
      get 'introduce'       #1 user co nhieu group
      resources :profiles          #1 user co nhieu group
      resources :memberlists do  #1 group co nhieu memberlists
        resources :profiles do
        end
      end
    end
  end

  resources :time_orders do
    resources :comments do
      post 'create'
    end
  end

  resources :welcome do
  end

  resources :attended_groups do
  end

  resources :comments do
    get 'create'
  end

  resources :groups do
    get 'profile'
  end

  resources :profiles do
    get 'show'
  end

end

metting_manager/app/models/group.rb
class Group < ActiveRecord::Base
	has_many :memberlists
	belongs_to :user
end

metting_manager/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  # GET /groups
  # GET /groups.json
  def index
   if current_user
    @groups = current_user.groups
  end
    # @groups = Group.all
  end
  # GET /groups/1
  # GET /groups/1.json
  def show 
    @group = Group.find_by_id(params[:id])
    @listmembers = @group.memberlists if @group.memberlists
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find_by_id(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    respond_to do |format|
      if @group.save
        format.html { redirect_to user_groups_path(current_user), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find_by_id(params[:id])
    @group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_path(current_user), notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    #binding.pry
  end

  def introduce

    @group = Group.find_by_id(params[:group_id])
    @time_order = TimeOrder.where(:group_id => params[:group_id]).sort_by {|vn| vn.time_start}
    if !params[:time_orde_id].nil?
      @timenow = TimeOrder.find_by_id(params[:time_orde_id])
    else
      c = Array.new
      @time_order.each{|t|
        if t.time_start.to_date == Time.now.to_date
          c.push(t)
        end
      }
      @timenow = c.sort_by {|vn| vn.time_start}.first if c.present?
    end
    if !params[:render].nil?
      respond_to do |format| 
        format.js
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :user_id, :desc)
    end
  end

metting_manager/app/views/groups/_form.html.erb
<style>

 header    {
background: -webkit-gradient(linear, bottom, left 175px, from(#CCCCCC), to(#EEEEEE));
background: -moz-linear-gradient(bottom, #CCCCCC, #EEEEEE 175px);
margin:auto;
margin-top :5%;
position:relative;
width:450px;
height:300px;
font-family: Tahoma, Geneva, sans-serif;
font-size: 14px;
font-style: italic;
line-height: 24px;
font-weight: bold;
color: #09C;
text-decoration: none;
-webkit-border-radius: 10px;
-moz-border-radius: 10px;
border-radius: 10px;
padding:10px;
border: 1px solid #999;
border: inset 1px solid #333;
-webkit-box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.3);
-moz-box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.3);
box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.3);
}

      
    }
  </style>
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <header>
    <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  <div class="field">
    <%= f.label :Admin %><br>
    <%= f.text_field :user_id, :value => Profile.find_by_id(current_user.id).name, :display => true %>

  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </header>
    
    
<% end %>

metting_manager/app/views/groups/_right_desc.html.erb
<% if @timenow == nil %>
    no meeting to day
  <%else%>
    <div >
      <% time_end = @timenow.time_end.strftime("%H").to_i+1 %>
      <li style="color: green;padding-top:5%;"><%= "#{@timenow.time_start.strftime("%H:%M")} to #{time_end}#{@timenow.time_end.strftime(":%M")}"  %><h1 style="color: Blue; pdding-top:5%;"> <%= @timenow.desc %> </h1></li>
    </div>
    <!-- comment -->
    <div id="commented">
      <%= render :partial => @timenow.comments if @timenow.comments %>
    </div>
    <!-- end comment -->

    <!-- create comment -->
    <div>
     <%= form_for([@timenow, @timenow.comments.build], remote: true) do |f| %>
     <p>
       <br>
       <%= f.text_area :desc ,id: 'desc_comment' %>
     </p>   
     <!--  -->
     <script>
       $('#desc_comment').keydown(function (e){
        if(e.keyCode == 13){
          var d = {desc: (this).value};
          $.ajax({
                 url: "<%= comment_create_path(@timenow,:time_order_id => @timenow.id) %>",
                type: "GET",
                data: { comment: d}
        });
        }
      })
     </script>
     <!--  -->
     <p><%= f.submit "Create comment",  id: "button", class: "btn btn-success green" %></p>
     <% end %>
   </div>
    <!-- end comment -->
 <%end%>

metting_manager/app/views/groups/_seach.html.erb
<p id="notice"><%= notice %></p>
<div style="display: inline-block">
  <%= form_for(@seach = "", url: users_search_path) do |f| %>
  <!-- loai tim kiem -->
    <% @find_style=["name","group"] %>
    <%= select_tag(:find_style, options_for_select(
            @find_style.collect{|u| 
                [u] }
    ))%>
      <!-- end loai tim kiem -->
    <%= f.text_field :name ,:style => "width:50%;"%>
    <%= f.hidden_field :group_id,:value => @group.id %>
    <%= f.submit "let go", :class => "btn-submit btn btn-info btn-sm" %>
  <% end %>
      <!-- drop menu setting -->
      <ul class="dropdown bs-example">
        <img  src=" /assets/setting.jpeg " data-toggle="dropdown" class="dropdown-toggle" width="15px" height="15px">
        <ul class="dropdown-menu">
          <li><%= link_to "add", new_user_group_memberlist_path(current_user,@group)%></li>
          <li><%= link_to 'Edit', edit_group_path(@group) %></li>
          <li><%= link_to 'Back', attended_groups_path(current_user) %></li>
        </ul>
      </ul>
    <!-- end drop menu setting -->
    <!-- lay lai db tu user -->
    <% @users = Array.new %>  <!-- khai bao 1 mang users moi de luu lai -->
    <% @groups = Array.new%>
    <% if !params[:listu].nil? %> <!-- neu prams khac nil thi ko thuc hien -->
        <%  params[:listu].each do |l| %><!-- voi moi phan tu list ta lam l-->
        <% @users.push(User.find_by_id(l)) %><!--dua vao moi @user la 1 id user-->
        <%   end %>
        <!-- render sau khi tim thay -->
        <% if @users!= nil%>
           <div style="width: 100%;display: inline-block;" >
          <!-- neu tim ra dc 2 mem tro len thi hien thi nut add all -->
              <%if @users.size > 1%>
                <div class="user_seach" style="">
                  <%= link_to user_group_memberlists_add_path(@group.user_id, @group,@users, :list => @users),:style => "background-color: lightblue;" do %>
                  <img  src="/assets/add-more-green-icone-8951-128.png" width="100%" height="100%" style="border: 3px solid red;
                  -moz-border-radius: 10px;
                  -webkit-border-radius: 10px;
                  -ms-border-radius: 10px;
                  -o-border-radius: 10px;
                  border-radius: 50%;
                  ">
                  <%end%>
            add all
          </div>
          <%end%>
          <%end%>
    <% elsif params[:listg]!=nil %>
       <%params[:listg].each do |k|%>
       <%  @groups.push(Group.find_by_id(k)) %>
       <%end%>

       <%@groups.each do |n|%>
       <% @users_group = Array.new %>
       <div  style=" display: inline-block; float:left" >
          <div style="background-color:red; display: inline-block; float:left">
           <%= n.name %></div><br>
           <!-- add all group -->
           <% @member_list = Memberlist.where(:group_id => n.id) %>
           <%  @member_list.each do |m| %>
             <% @user = User.find_by_id(m.user_id) %>
             <% @users_group.push(@user) %>
             <%= render :partial => @user %>
            <%end%>
                <div class="user_seach" style="">
                  <%= link_to user_group_memberlists_add_path(@group.user_id, @group,@users_group, :list => @users_group), data: { confirm: 'Are you sure add they?' } , :style => "background-color: lightblue;" do %>
                  <img  src="/assets/add-more-green-icone-8951-128.png" width="100%" height="100%" style="border: 3px solid red;
                  -moz-border-radius: 10px;
                  -webkit-border-radius: 10px;
                  -ms-border-radius: 10px;
                  -o-border-radius: 10px;
                  border-radius: 50%;
                  ">
                  <%end%>
            add all
          </div>
       </div>
       
       <br>

       <%end%>
      <!-- end add all group -->

    <% end %>
        <!-- end add all button -->
        <% @users.each do |u| %>
        <% @user = User.find_by_id(u.id) %>
        <%= render :partial => @user %>
        <% end %>
    
</div>

metting_manager/app/views/groups/_show_member.html.erb
  <!-- render -->
  <div class="member">
    <div id = "review">
        <%= render :partial => @group.memberlists %>
    </div>
  </div>

metting_manager/app/views/groups/_time_order.html.erb
<!-- doi mau  -->
<% if @timenow!=nil && time == @timenow %>
  <li class="mnav-ul-li" >
  <% h_time_end = time.time_end.strftime("%H").to_i + 1 %>
  <a style="color: #99FF33"><%= "#{time.time_start.strftime("%H:%M")} to #{h_time_end}#{time.time_end.strftime(":%M")}" %> </a>
  <ul class="mnav-ul-ul"> 
    <li lass="desc_time_order"><%= link_to "#{time.desc}",user_group_introduce_path(params[:user_id],@group,:time_orde_id => time,:render => "true"), :style => "color: #99FF33",remote: true %></li>
  </ul>
</li>
<!-- khong doi mau -->
<% else %>
  <li class="mnav-ul-li" style="color: red;">
  <% h_time_end = time.time_end.strftime("%H").to_i + 1 %>
  <a><%= "#{time.time_start.strftime("%H:%M")} to #{h_time_end}#{time.time_end.strftime(":%M")}" %> </a>
  <ul class="mnav-ul-ul"> 
    <li class="desc_time_order"><%= link_to "#{time.desc}",user_group_introduce_path(params[:user_id],@group,:time_orde_id => time,:render => "true"),remote: true %></li>
  </ul>
</li>
<% end %>

metting_manager/app/views/groups/add.html.erb
<!DOCTYPE <!DOCTYPE html>
<html>
<head>
<title>them</title>
</head>
<body>
<%= form_tag "/add"%>
<%= label_tag "name"%><td><br>
<%= text_field_tag :name, params[:name]%><br>
<%= label_tag "desc"%><td><br>
<%= text_field_tag :desc, params[:desc]%><br>
<br>
<%= submit_tag "ok"%>
</body>
</html>

metting_manager/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

metting_manager/app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.user_id %></td>
        <td><%= group.desc %></td>
        <td><%= link_to 'Show', user_group_path(current_user, group) %></td>
        <td><%= link_to 'Edit', edit_user_group_path(current_user, group) %></td>
        <td><%= link_to 'Destroy', user_group_path(current_user,group), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_user_group_path(current_user) %>

metting_manager/app/views/groups/introduce.html.erb
<div class="group_header">
  <p> <%= @group.name.upcase %>  /   
    <%= link_to "#{@group.memberlists.size + 1} members",user_group_path(params[:user_id],@group) %>
  </p>
</div>
<!-- reder seach -->
<div>
    <%= render 'seach' %>
</div>
<!-- in lich -->
<!-- phan ben  trai -->
<div id="time_order" class="col-xs-2 col-sm-3 col-md-3 col-lg-3 mg-top-15">
<% if !@time_order.blank? %>
  <% @time_prev = @time_order.first.time_start %>
  <% @time_last = @time_order.last %>
  <li class="mnav-ul-li"> 
    <%= render partial: 'time_orders/color_time', locals: {time: @time_order.first} %>
  <ul class="mnav-ul-ul">
  <% @time_order.each do |time| %>
    <% if time.time_start.to_date > @time_prev.to_date %>
        </ul></li>
        <% @time_prev = time.time_start.to_date %>
        <li class="mnav-ul-li">
        <%= render partial: 'time_orders/color_time', locals: {time: time} %>
        <ul class="mnav-ul-ul">
        <%= render partial: "time_order", locals: { time: time } %>
    <% elsif time == @time_last %>
      </ul>
      </li>

    <% else %>
      <%= render partial: "time_order", locals: { time: time } %>
    <%end%>
    
  <%end%>
<%end%>
</div>

<script type="text/javascript">
  $('#time_order').on('click', '.mnav-ul-li a', function(){
//alert( 'clicked' );
//$(this).parent().find('ul>li:first').slideToggle();
//$(this).find('ul:first > li').slideToggle();
$(this).parent().find('ul:first > li').slideToggle();
$(this).parent().find('ul:first > li').css({ 
  "display": "block",
  "width": "200px", 
});
}); 
</script>

<!-- phan ben phai -->
<div class="col-xs-4 col-sm-6 col-md-6 col-lg-8 pg-top-15" id="right_full_desc">
  <%= render partial: "right_desc" %>
</div>
<!-- end in lich -->

metting_manager/app/views/groups/introduce.js.erb
$("#right_full_desc").html("<%= escape_javascript(render(:partial => 'right_desc')) %>");

metting_manager/app/views/groups/new.html.erb
<style type="text/css">
 .newclass{
background: -webkit-gradient(linear, bottom, left 175px, from(#CCCCCC), to(#EEEEEE));
background: -moz-linear-gradient(bottom, white, #EEEEEE 175px);
margin:auto;
position:relative;
width:100%;
height:60px;
font-family: Tahoma, Geneva, sans-serif;
font-size: 14px;
font-style: italic;
line-height: 14px;
font-weight: bold;
color: #09C; 
text-decoration: none;
-webkit-border-radius: 10px;
-moz-border-radius: 10px;
border-radius: 10px;
padding:10px;
border: 1px solid white;
border: inset 1px solid #333;
-webkit-box-shadow: 0px 0px 4px rgba(0, 0, 0, 0.3);
-moz-box-shadow: 0px 0px 4px rgba(0, 0, 0, 0.3);
box-shadow: 0px 0px 4px 4px  rgba(0, 0, 0, 0.3);
}
}
</style>
<head>
	<div class="newclass" style = "width:100%"><h1 style="margin:auto">New Group</h1></div>

<%= render 'form' %>

<%= link_to 'Back', user_groups_path(current_user) %>


</head>

metting_manager/app/views/groups/search.js.erb
window.onload = function(){
	alert("abc");
  document.getElementById('linkmem').click();
};

metting_manager/app/views/groups/show.html.erb
<div class="group_header">
  <p> <%= link_to "#{@group.name.upcase}",user_group_introduce_path(params[:user_id],@group)  %>  /   
    <%= @group.memberlists.size + 1 %>  members
  </p>
</div>
<!-- reder seach -->
<%= render 'seach' %>
<!-- render -->
<div class="member">
  <div id = "review">
    <%= render :partial => @group.memberlists %>
  </div>
</div>
</div>