metting_manager/config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :groups
  get 'groups/index'
  get 'users/search'
  post 'users/search'
  get 'users/index'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: 'users/registrations',
                                }
  root 'welcome#index'
  resources :users do            #tao moi quan he trong chung
    resources :profiles do
    end
    resources :groups do  
      get 'memberlists/add'
      post 'memberlists/add'
      get 'introduce'       #1 user co nhieu group
      resources :profiles          #1 user co nhieu group
      resources :memberlists do  #1 group co nhieu memberlists
        resources :profiles do
        end
      end
    end
  end

  resources :time_orders do
    resources :comments do
      post 'create'
    end
  end

  resources :welcome do
  end

  resources :attended_groups do
  end

  resources :comments do
    get 'create'
  end

  resources :groups do
    get 'profile'
  end

  resources :profiles do
    get 'show'
  end

end

metting_manager/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :groups
   has_one :profile
   has_many :time_orders
   has_many :comments
   
   def self.create_user(user)
     User.create(email: user[:email],password: user[:password])
   end
   
  def admin?
    if self.id.nil?
       false
    else
      self.role_id ==1   
    end 
  end

  def user?
    if self.id.nil?
        false
    else
        self.role_id ==2 || self.role_id ==3
    end 
  end

end

metting_manager/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

metting_manager/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

metting_manager/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

metting_manager/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
    @user = User.new
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    @user = current_user
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :attribute
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :attribute
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    Profile.create_profile(current_user.id,params[:profile][:name])
    root_path(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    # binding.pry
    super(resource)
  end
end

metting_manager/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

metting_manager/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

metting_manager/app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def index
  end
  
  def search
    @users = Array.new
    @groups =Array.new 
    @group = Group.find_by_id(params[:group_id])#giup dieu huong phai lay group_id
    if params[:find_style]=="name"&&(@profiles = Profile.where(["name LIKE ?", "%#{params[:name]}%"]))!=nil
       #:name => params[:name]
       #lay param chuyen len
       @profiles.each do |f| #voi moi cac profiles ta day cac user id vao mang @user
        @users.push(User.find_by_id(f.user_id))
       end
       redirect_to user_group_path(@group.user_id,@group, :listu => @users)
    elsif (@group_name = Group.where(["name LIKE ?", "%#{params[:name]}%"]))!=nil
    
      @group_name.each do |x|
       @groups.push( Group.find_by_id(x.id))
      end
     redirect_to user_group_path(@group.user_id,@group, :listg => @groups)#show trang group sho
    end
  end
end

metting_manager/app/helpers/users_helper.rb
module UsersHelper
end

metting_manager/app/views/users/_user.html.erb
<!--voi moi users ta hien name va cac group ma chung tham gia cua chung -->
<% @team = ""%>
<% @mem = Memberlist.where(:user_id => @user.id) %>
<%  if @mem.size > 1
  @mem.each{|u| 
    @team = @team + "<br>==>"+ Group.find_by_id(u.group_id).name
  } %>
  <%  elsif @mem.size==1
  @team =  Group.find_by_id(@mem[0].group_id).name;
end
%>
<% value ="1.Name => " + @user.profile.name + "<br>" + "2.Teams:  "+ @team%>
<!-- value cho tootip -->
<!-- end -->

<div class="user_seach" onmouseover="bigDivu(this)" onmouseout ="normalDivu(this)"  data-html="true" data-toggle="tooltip" data-placement="top" title = "<%= value%>" >
  <%= link_to user_profile_path(@user.id, @user.profile) do %>
  <%= image_tag(@user.profile.picture_url,:class => "myimg1",:width => "100%",:height => "100%",:style => "  border: 3px solid #686868;
    -moz-border-radius: 10px;
    -webkit-border-radius: 10px;
    -ms-border-radius: 10px;
    -o-border-radius: 10px;
    border-radius: 50%;
    ")%>
    <%= link_to user_group_memberlists_add_path(@group.user_id, @group, @user) do%>

    <img  src=" /assets/add-more-green-icone-8951-128.png" width="15px" height="15px">
    <% end %>
    <%= @user.profile.name %>
    <% end%>
  </div>

  <script>
    function bigDivu(x) {
      x.style = " border-radius: 50%;; -moz-border-radius: 10px; -webkit-border-radius: 10px; -ms-border-radius: 10px; -o-border-radius: 10px;box-shadow: 0px 0px 3px 3px darkgrey ;width:90px; height: 90px;";
    }
    function normalDivu(x) {
      x.style = "border: 0px;width:90px; height: 90px"; 
      x.getElementsByClassName("myimg1")[0].style = "border: 3px solid #686868;border-radius: 50%; -moz-border-radius: 10px; -webkit-border-radius: 10px; -ms-border-radius: 10px; -o-border-radius: 10px;";
      x.attr('data-toggle', 'disabled');
    }
  </script>

metting_manager/app/views/users/session.html.erb
<h2>Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>