metting_manager/config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :groups
  get 'groups/index'
  get 'users/search'
  post 'users/search'
  get 'users/index'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: 'users/registrations',
                                }
  root 'welcome#index'
  resources :users do            #tao moi quan he trong chung
    resources :profiles do
    end
    resources :groups do  
      get 'memberlists/add'
      post 'memberlists/add'
      get 'introduce'       #1 user co nhieu group
      resources :profiles          #1 user co nhieu group
      resources :memberlists do  #1 group co nhieu memberlists
        resources :profiles do
        end
      end
    end
  end

  resources :time_orders do
    resources :comments do
      post 'create'
    end
  end

  resources :welcome do
  end

  resources :attended_groups do
  end

  resources :comments do
    get 'create'
  end

  resources :groups do
    get 'profile'
  end

  resources :profiles do
    get 'show'
  end

end

metting_manager/app/models/memberlist.rb
class Memberlist < ActiveRecord::Base
	has_many :users
	belongs_to :group
  has_many :profiles
	

	def self.search(search)
	  search_condition = "%" + search + "%"
	  find(:all, :conditions => ['title LIKE ? OR description LIKE ?', search_condition, search_condition])
	end
end

metting_manager/app/controllers/memberlists_controller.rb
class MemberlistsController < ApplicationController

	def new
    @group = Group.find_by_id(params[:group_id]) 
    @member = Memberlist.new
  end

  def add 
    @listtam = params[:list]
   
    @this_user = User.find_by_id(params[:user_id])
    @this_group = Group.find_by_id(params[:group_id])
    if @listtam != nil 
       @list = Array.new
      @listtam.each do |f|
        @list.push(f)
      end
      @listtam.each do |f| 
        @member = User.find_by_id(f)
        if Memberlist.find_or_create_by(:group_id => @this_group.id,:user_id => @member.id)
          @list.delete("#{@member.id}")  #xoa cac pt trong list tuong ung
        end
      end
    else #su dung voi add 1 user
      @member = User.find_by_id(params[:format])
      Memberlist.find_or_create_by(:group_id => @this_group.id,:user_id => @member.id)
    end
    # binding.pry
    redirect_to user_group_path(@this_user,@this_group, :list => @list)
  end
#   def search
#   @member = Memberlist.search params[:search]
# end
def show
    @member = Memberlist.find_by_id(params[:id])
    @user = User.find_by_id(@member.user_id)
  end

  def destroy
    @memberlist = Memberlist.find_by_id(params[:id])
    @memberlist.destroy
    respond_to do |format|
     format.html { redirect_to user_group_path(User.find_by_id(params[:user_id]), Group.find_by_id(params[:group_id])), notice: 'Group was successfully destroyed.' }
     format.json { head :no_content }
   end
 end

 def create
      #binding.pry
      @memberlist = Memberlist.new(:user_id => params[:memberlist][:user_id], :group_id => params[:group_id])

      respond_to do |format|
        if @memberlist.save
          format.html { redirect_to user_group_path(current_user,Group.find_by_id(params[:group_id])), notice: 'Group was successfully created.' }
          format.json { render :show, status: :created, location: @memberlist }
        else
          format.html { render :new }
          format.json { render json: @memberlist.errors, status: :unprocessable_entity }
        end
      end
    end

  end

metting_manager/app/views/memberlists/_memberlist.html.erb
<% @profile=Profile.find_by_user_id(memberlist.user_id)%>
<% value  = "team =>" + @group.name  + "<br>" + "name => " + @profile.name + "<br>" + "level=> " + @profile.level%>
    <div class="review_<%=h memberlist.user_id %> sub_member test" onmouseover="bigDiv(this)" onmouseout ="normalDiv(this)" style="border: 10px; border-color: red" data-html="true" data-toggle="tooltip" data-placement="top" title = "<%= value%>" >

    <%= link_to user_profile_path(memberlist.user_id, @profile) do %>
            <%= image_tag(@profile.picture_url,:class => 'myimg',:width => "100%",:height => "90%",:style => "border: 5px solid lightblue;
                        -moz-border-radius: 10px;
                        -webkit-border-radius: 10px;
                        -ms-border-radius: 10px;
                        -o-border-radius: 10px;
                        border-radius: 10px;
                        border-color: DeepSkyBlue"
    )%>
    <% end %>

    <%= link_to "#{@profile.name}",user_group_memberlist_profile_path(@group.user_id,@group,memberlist,@profile)%>
    <td><%= link_to 'Destroy', user_group_memberlist_path(current_user,@group,memberlist), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    
  </div>  
<!--  -->
<script>
function bigDiv(x) {
  x.style = " border-radius: 10px; border-color: red; -moz-border-radius: 10px; -webkit-border-radius: 10px; -ms-border-radius: 10px; -o-border-radius: 10px;box-shadow: 0px 0px 4px 4px grey;";
  x.getElementsByClassName("myimg")[0].style = "border:0px";
  // x.style = "border: 5px solid lightblue;";
  // x.style = "-moz-border-radius: 10px;";
  // x.style = " -webkit-border-radius: 10px;";
  // x.style = "  -ms-border-radius: 10px;";
  // x.style = "  -o-border-radius: 10px;";
  // x.style = " border-radius: 10px; border-color: DodgerBlue   ";
  // lam sang anh
  // x.style.opacity = "1";
  // x.style.filter ="alpha(opacity=1000);"
  // x.style.width = "200px";
  // x.style.height = "200px";
}
function normalDiv(x) {
   x.style = "border: 0px";
  x.style.width = "17%";
  x.style.height = "180px";
  x.getElementsByClassName("myimg")[0].style = "border: 5px solid DeepSkyBlue;border-radius: 10px; -moz-border-radius: 10px; -webkit-border-radius: 10px; -ms-border-radius: 10px; -o-border-radius: 10px;";
  // x.style = "border: 0px";
  // x.style.width = "180px";
  // x.style.height = "180px";
  // x.style.opacity = "0.4"; lam mo anh
  // x.style.filter = ": alpha(opacity=40)";
}
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
 </script>

metting_manager/app/views/memberlists/create.js.erb
$("#reviews").append("<%= escape_javascript(render(:partial => @comment)) %>");

metting_manager/app/views/memberlists/destroy.js.erb
var r=confirm("Are you sure you want to delete?");
if (r==true){
$(".review_<%= memberlist.user_id %>").remove(); }