metting_manager/config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :groups
  get 'groups/index'
  get 'users/search'
  post 'users/search'
  get 'users/index'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: 'users/registrations',
                                }
  root 'welcome#index'
  resources :users do            #tao moi quan he trong chung
    resources :profiles do
    end
    resources :groups do  
      get 'memberlists/add'
      post 'memberlists/add'
      get 'introduce'       #1 user co nhieu group
      resources :profiles          #1 user co nhieu group
      resources :memberlists do  #1 group co nhieu memberlists
        resources :profiles do
        end
      end
    end
  end

  resources :time_orders do
    resources :comments do
      post 'create'
    end
  end

  resources :welcome do
  end

  resources :attended_groups do
  end

  resources :comments do
    get 'create'
  end

  resources :groups do
    get 'profile'
  end

  resources :profiles do
    get 'show'
  end

end

metting_manager/app/models/profile.rb
class Profile < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user
  belongs_to :memberlist

  attr_accessor :is_thumbnable

  def to_param
    name
  end
  
  def self.create_profile(user_id,name)
    Profile.create!(user_id: user_id,name: name)
  end
  
  def self.edit_profile(user_id,profile)
    binding.pry
    Profile.find_by_user_id(user_id).update_by(name: profile[:name],level: profile[:level],picture: profile[:picture])
  end

end

metting_manager/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @this_user = User.find_by_id(params[:user_id])
    @this_profile = @this_user.profile
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @this_user = User.find_by_id(params[:user_id])
    @this_profile = @this_user.profile
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    # binding.pry
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile}
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to user_profile_path(@profile.user_id, @profile), notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find_by_user_id(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :level, :picture)
    end
end

metting_manager/app/helpers/profiles_helper.rb
module ProfilesHelper
end

metting_manager/app/views/profiles/_form.html.erb
<%= form_for(@this_profile, html: { multipart: true }, url: user_profile_path(@this_profile.user_id, @this_profile)) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field"><br>
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>

  <div class="picture"><br>
    <%= f.label :avatar %><br>
    <%= f.file_field :picture %>
  </div>

  <div class="actions">  <br>
    <%= f.submit "update",:class => "btn btn-primary"%>
  </div>

<% end %>

metting_manager/app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>
<%= render 'form' %>
<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

metting_manager/app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Profiles</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Picture</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.level %></td>
        <td><%= profile.picture %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', user_profile_path(profile.user_id, profile) %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(profile.user_id, profile) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

metting_manager/app/views/profiles/new.html.erb
<h1>New Profile</h1>
<%= render 'form' %>
<%= link_to 'Back', profiles_path %>

metting_manager/app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @this_profile.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @this_profile.level %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @this_profile.picture %>
</p>
<div class="picture">
	<%= image_tag(@profile.picture_url, :width => 600) if @profile.picture.present? %>
</div>

<%= link_to 'Edit', edit_user_profile_path(@this_profile.user_id, @this_profile)%> |
<% if @group != nil %>
<%= link_to 'Back', user_group_path(current_user,@group) %>
<%else%>
<%= link_to 'Back', profiles_path %>
<%end%>